oauth2_jwt_sso.settings:
  type: config_object
  label: 'OAuth2 JWT SSO Settings'
  mapping:
    authorization_url:
      type: uri
      label: 'Authorization URL'
      description: ''
    access_token_url:
      type: uri
      label: 'Access Token URL'
      description: ''
    logout_url:
      type: uri
      label: 'Logout URL'
      description: ''
    client_id:
      type: string
      label: 'Client ID'
      description: ''
    client_secret:
      type: string
      label: 'Client Secret'
      description: ''
    auth_public_key:
      type: text
      label: 'Auth Server Public Key'
      description: 'The public key'
